CREATE DATABASE game;
USE game;
CREATE TABLE user(id VARCHAR(50), pw TEXT, PRIMARY KEY(id) )ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE player(id VARCHAR(50),data BLOB,PRIMARY KEY(id) )ENGINE=InnoDB DEFAULT CHARSET=utf8; 
