CREATE DATABASE game;
USE game;
CREATE TABLE user(id VARCHAR(50), pw TEXT, PRIMARY KEY(id) )ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE player(id VARCHAR(50),data BLOB,PRIMARY KEY(id) )ENGINE=InnoDB DEFAULT CHARSET=utf8; 

CREATE TABLE DAU(day DATE, dau INT, PRIMARY KEY(day) )ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO user values("test", "test");
